spring:
  application:
    name: microservice2
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres14:5432}/${DB_DATABASE:dbtest}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:max123}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9091
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
      root: DEBUG
