spring:
  application:
    name: microservice3
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres14:5432}/${DB_DATABASE:dbtest}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:max123}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
server:
  port: 8083
logging:
  level:
    org.hibernate.SQL: debug
